#!/usr/bin/env python

import argparse
import re
import os
import shutil

parser = argparse.ArgumentParser(description='File your media files.')
parser.add_argument('filesOrDirectories', metavar='file', type=str, nargs='+',
				   help='files or directories to file')
parser.add_argument('-o', '--output', dest='destination', type=str,
				   help='the destination directory for the files')
parser.add_argument('-s', '--simulate', dest='simulate', action='store_true',
				   help='don\'t actually move or rename, just simulate')
parser.set_defaults(simulate=False)

args = parser.parse_args()

episodematcher = re.compile('(.*)[sS](\d\d)[eE](\d\d)(.*)')
convertedmatcher = re.compile('(.*)\.(\d?\d)(\d\d)\.mp4')
def findSeasonEpisode(s):
	if "sample" in s.lower():
		return ("", 0, 0)
	m = episodematcher.search(s)
	if m == None:
		m = convertedmatcher.search(s)
		if m == None:
			return ("", 0, 0)

	show = "".join([part[:1].upper() + part[1:].lower() for part in re.split('[ \.-]', m.group(1))])
	show = re.sub('[\']', '', show)
	season = int(m.group(2))
	episode = int(m.group(3))
	return (show, season, episode)

moviematcher = re.compile('(.*)\.mp4')
def handleFile(file):
	fileName = os.path.basename(file)

	# only check movies
	m = moviematcher.search(fileName)
	if m == None:
		return

	# try to extract the show info from the filename
	show, season, episode = findSeasonEpisode(fileName)
	if len(show) <= 0:
		# filename didn't work, now try the parent directory
		dirName = os.path.split(os.path.dirname(file))[1]
		show, season, episode = findSeasonEpisode(dirName)
		if len(show) <= 0:
			return

	if args.destination == None:
		destFolder = directory
	else:
		destFolder = os.path.join(args.destination, show, "season%02d" % season)
	destFileName = "%s.%d%02d.mp4" % (show, season, episode)
	destFile = os.path.join(destFolder, destFileName)

	if args.simulate:
		print "[SIMULATED] moving %s to %s" % (file, destFile)
		return

	if not os.path.exists(destFolder):
		os.makedirs(destFolder)

	shutil.move(file, destFile)
	print file, " moved to ", destFile

def handle(directory, fileOrDirectory):
	fullPath = os.path.join(directory, fileOrDirectory)
	if os.path.isdir(fullPath):
		for child in os.listdir(fullPath):
			handle(fullPath, child)
	else:
		handleFile(fullPath)

for fileOrDirectory in args.filesOrDirectories:
	handle(os.getcwd(), fileOrDirectory)
